src/Entity/RMARequestInterface.php
<?php

namespace Ikuzo\SyliusRMAPlugin\Entity;

use Doctrine\Common\Collections\Collection;
use Sylius\Component\Channel\Model\ChannelInterface;
use Sylius\Component\Order\Model\OrderInterface;
use Sylius\Component\Product\Model\ProductVariantInterface;
use Sylius\Component\Resource\Model\ResourceInterface;
use Sylius\Component\Resource\Model\TimestampableInterface;

interface RMARequestInterface extends ResourceInterface, TimestampableInterface
{
    public function getId(): ?int;

    public function getChannel(): ?ChannelInterface;
    public function setChannel(?ChannelInterface $channel): void;
    
    public function getOrder(): ?OrderInterface;
    public function setOrder(?OrderInterface $order): void;

    public function getVariants(): ?Collection;
    public function hasVariant(ProductVariantInterface $variant): bool;
    public function addVariant(ProductVariantInterface $variant): void;
    public function removeVariant(ProductVariantInterface $variant): void;

    public function getReason(): string;
    public function setReason(string $reason): void;

    public function getComment(): string;
    public function setComment(string $comment): void;

    public function getState(): string;
    public function setState(string $state): void;
}

src/Resources/views/Grid/Action/accept.html.twig
{% set path = options.link.url|default(path(options.link.route, options.link.parameters)) %}

{% if data.state in ['requested'] %}
    <form action="{{ path }}" method="post" novalidate>
        <input type="hidden" name="_csrf_token" value="{{ csrf_token(data.id) }}" />
        <input type="hidden" name="_method" value="PUT">
        <button type="submit" class="ui icon labeled tiny green fluid loadable button"><i class="check icon"></i> {{ action.label|trans }}</button>
    </form>
{% endif %}

src/Resources/views/Grid/Action/refuse.html.twig
{% set path = options.link.url|default(path(options.link.route, options.link.parameters)) %}

{% if data.state in ['requested'] %}
    <form action="{{ path }}" method="post" novalidate>
        <input type="hidden" name="_csrf_token" value="{{ csrf_token(data.id) }}" />
        <input type="hidden" name="_method" value="PUT">
        <button type="submit" class="ui icon labeled tiny red fluid loadable button"><i class="times icon"></i> {{ action.label|trans }}</button>
    </form>
{% endif %}

src/Resources/views/Grid/Action/send_rma.html.twig
{% import '@SyliusUi/Macro/buttons.html.twig' as buttons %}

{% set path = options.link.url|default(path(options.link.route, options.link.parameters)) %}

{% if data.state in ['fulfilled'] %}
    {{ buttons.default(path, action.label, null, 'mail', 'purple') }}
{% endif %}